%% extrude_mesh
% 
% <msim_help_main.html | main>   <msim_help_demos.html | Tutorials> 
% <msim_function_categories.html | Functions> <http://www.subsurface.gr | website> |
%
% Extrudes a 2D mesh to 3D. If the 2D mesh has triangular elements the 3D
% elements will be prisms. If the 2D mesh has quadrilaterals then the 3D
% elements will be hexahedral.
%
% Version : 1.0
%
% Author : George Kourakos
%
% email: giorgk@gmail.com
%
% web : http://groundwater.ucdavis.edu/msim
%
% Date 18-Mar-2014
%
% Department of Land Air and Water
%
% University of California Davis
%
%% Usage
% [p MSH]=extrude_mesh(p_2d, MSH_2d, top, bot, t, el_order)
%
%% Input
% _*p_2d*_: Coordinates of 2D mesh nodes
%
% _*MSH_2d*_: Mesh structure generated by Gmsh.
%
% _*top*_: top elevation of the 2D mesh nodes
%
% _*bot*_: bottom elevation of the 2D mesh nodes
%
% _*t*_: parametric variable that defines how many layers will be generated 
% and their vertical distribution between the
% top and bottom elevation. The _*t*_ values must be t(1) = 0 
% (corresponds to bottom elevation) and t(end) = 1 (coresponds to top elevation)
% A quick way to plot the layer distribution is plot(ones(length(t),1),t,'.-')
%
% _*el_order*_:element order 'linear' or 'quadratic'. At the moment incomplete
% elements are not supported
%
%% Output
% _*p*_: coordinates of 3D mesh nodes
%
% _*MSH*_ 3D mesh structure.
%
% see also: <Centerfor2points_help.html Centerfor2points>
%%
% 
% <msim_help_main.html | main>   <msim_help_demos.html | Tutorials> 
% <msim_function_categories.html | Functions> <http://www.subsurface.gr | website> |
%
